feat(contact): add validation name and email
jainemarindasilva/coisas_emprestadas pull request #3
Opened 2022-03-10 17:36 UTC by jainemarindasilva

:chart_with_downwards_trend: [Card Link](https://trello.com/c/tVdz9U5B)

## Motivation :muscle:

Melhorar a listagem dos contatos e realizar validações nos campos de nome e email.

## Solution :wrench:

- Utilização do [Materialize](https://materializecss.com/) para formatar o html da lista de contatos;
- Implementado `active_validations` no model contact.

## How to test :policeman:

1. Abrir a tela de listagem de contatos: /contacts/
2. Adicionar um registro clicando no botão "add" (ou através da rota contacts/new)
3. Editar o contato criado através da tela de listagem, clicando no botão de "lápis"
4. Excluir o contato criado através da tela de listagem, clicando no botão de "lixeira"

## Images/Gifs

2022-03-10 18:01 UTC, BrunoHoffmann15 requested changes

2022-03-10 18:44 UTC, muriloazevedo requested changes
apenas uma alteração importante no controller, o resto é sugestão. Tá ótimo! 😁

2022-03-10 18:44 UTC, muriloazevedo commented on app/controllers/contacts_controller.rb
> +    if newContact.valid?
melhor fazer a da seguinte forma:
````ruby
    newContact = Contact.new(contact_params)
    if newContact.save
       redirect_to action:"index", status: :see_other
````

A explicação é que o create faz as tarefas de `.new` e `.save` de uma vez. Dessa forma, o if `.valid?` acaba sendo redundante. Também tem a questão de que isso acaba tentando uma inserção no banco e fazendo um possível rollback caso o registro seja inválido.

2022-03-10 18:44 UTC, muriloazevedo commented on app/controllers/contacts_controller.rb
> +      render json: {errors:  newContact.errors.full_messages},
no caso precisamos apenas renderizar o form novamente:

````ruby
render :new

2022-03-10 18:44 UTC, muriloazevedo commented on app/controllers/contacts_controller.rb
> +    redirect_to action:"index", status: :see_other
apenas sugestão:

````ruby 
redirect_to :index, status: :see_other

2022-03-10 18:50 UTC, muriloazevedo commented
@jainemarindasilva @gabriellaxaviera quase esqueci. seria bom uma migration para garantir que nosso banco não possui registros duplicados, ex:

https://riptutorial.com/ruby-on-rails/example/5941/add-an-unique-column-to-a-table

2022-03-11 12:25 UTC, merged

2022-03-11 12:26 UTC, jainemarindasilva commented
Realizado ajustes pontuados.